servicename: groups
tracing:
  enabled: true
  type: zipkin
  url: http://localhost:9411/api/v1/spans
data:
  type: pg
  pg:
    host: localhost
    port: 5432
    user: es
    password: mysecret
    name: eventstore
stream:
  type: "pubsub"
  pubsub:
    projectid: nordic-gaming
    topicid: eventstore-examples